######################################################################
# Automatically generated by qmake (2.01a) Mi. Sep 14 15:02:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Bewohner.hxx \
           database.hxx \
	   Mitarbeiter.hxx \
           Projekt.hxx \
           Wohngruppe.hxx \

SOURCES += database.cxx \
           Mitarbeiter.cxx \
