######################################################################
# Automatically generated by qmake (2.01a) Fr. Sep 9 14:36:35 2011
######################################################################

TEMPLATE = subdirs

# Directories

SUBDIRS += \
    AdminDialog

