######################################################################
# Automatically generated by qmake (2.01a) Mi. Okt 19 11:54:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cxx
